FROM apache/airflow:2.9.0
USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
            vim \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
USER airflow
